### ISSUE TITLE
Address en-/decoding issues when R/W-ing files

### ISSUE THREAD

**Issue by iiegn** [elexis-eu/lexonomy#140]
On my Chromebook, running Xubuntu 16.04, I get a different error when running `lexonomy.py`:
```
$ python3.6 lexonomy.py 
Traceback (most recent call last):
  File "lexonomy.py", line 4, in <module>
    import os, sys, json, sqlite3, functools, ops
  File "/home/jan/projects/tmp/lexonomy/website/ops.py", line 5, in <module>
    siteconfig = json.load(open(os.environ.get("LEXONOMY_SITECONFIG", "siteconfig.json")))
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1301: ordinal not in range(128)
```

_Originally posted by @jan-niestadt in https://github.com/elexis-eu/lexonomy/issues/133#issuecomment-501159968_

**Comment by iiegn** [comment]
@gareins said in https://github.com/elexis-eu/lexonomy/issues/133#issuecomment-501172990

> first, check if LEXONOMY_SITECONFIG is defined as environment variable
>
> $ [[ -v LEXONOMY_SITECONFIG ]]; echo $?
>
> Let's say its not defined (there is 1 in stdout). Next, check if "./siteconfig.json" is proper ascii file:
>
> $ file ./siteconfig.json
>
> If it says it is utf-8, then you could change that line to force utf-8 decode:
>
>> configfile = os.environ.get("LEXONOMY_SITECONFIG", "siteconfig.json")
>> json.loads(open(configfile, 'rb').read().decode('utf8'))
>
> Although this should be the default by my pythonic standards, but here you get a strange ascii decode error, so try this.
